import test from 'node:test';
import assert from 'node:assert/strict';
import * as T from 'three';
import {readFileSync,existsSync} from 'node:fs';
import {CATALOG,PRESETS,preset,item,definitions,itemWarnings,findPath,destination,navObstacles,pointBlocked,personRadius,overlap,worldPoint,localPoint,validateLayout,pieces,FLOOR,WALLS} from '../src/core.js';
import {furnitureModel,buildHouse,makePerson,disposeModel} from '../src/models.js';

for(const {id} of PRESETS){
 test(`${id}: no default object, wall or door-clearance overlaps`,()=>{const items=preset(id);for(const o of items)assert.deepEqual(itemWarnings(o,items).filter(x=>!x.startsWith('Loft:')),[],o.type);});
 test(`${id}: all five destinations reachable at 170 cm`,()=>{const items=preset(id);for(const action of ['bed','desk','bathroom','balcony','entrance']){const p=destination(action,items).map(d=>findPath({x:0,z:1.3},d,items)).find(Boolean);assert.ok(p,action);const obs=navObstacles(items),radius=personRadius(1.7);for(let i=1;i<p.length;i++){assert.equal(pointBlocked(p[i].x,p[i].z,obs,radius),false,action);for(let j=1;j<5;j++){const t=j/5,x=p[i-1].x+(p[i].x-p[i-1].x)*t,z=p[i-1].z+(p[i].z-p[i-1].z)*t;assert.equal(pointBlocked(x,z,obs,radius),false,`${action}: segment ${i}`);}}}});
}
test('flex: unfolded bed remains collision-free and reachable',()=>{const items=preset('flex'),sofa=items.find(o=>o.type==='sofabed');sofa.open=true;for(const o of items)assert.deepEqual(itemWarnings(o,items),[],o.type);assert.ok(destination('bed',items).some(d=>findPath({x:0,z:1.3},d,items)));});
test('blocking the front door prevents a false positive',()=>{const items=[item('wardrobe',0,2.22,0,{w:2.10,d:.6})];assert.equal(findPath({x:0,z:1},{x:0,z:2.02},items),null);});
test('outside-domain and non-finite targets are rejected',()=>{for(const end of [{x:7,z:0},{x:0,z:-7},{x:NaN,z:1},{x:Infinity,z:0}])assert.equal(findPath({x:0,z:1},end,[]),null);});
test('room, bathroom and fixed glass pane block pedestrians; door passages do not',()=>{assert.equal(pointBlocked(-2.175,-1,WALLS),true);assert.equal(pointBlocked(-2.175,.05,WALLS),false);assert.equal(pointBlocked(-.5,2.30,WALLS),false);assert.equal(pointBlocked(.5,2.30,WALLS),true);});
test('rotation inverse and oriented collision agree',()=>{const a={x:1,z:-1,w:1,d:2,rot:Math.PI/3};const p=worldPoint(a,.2,.7),back=localPoint(a,p.x,p.z);assert.ok(Math.abs(back.x-.2)<1e-9);assert.ok(Math.abs(back.z-.7)<1e-9);assert.equal(overlap(a,{...a,x:1.1}),true);assert.equal(overlap(a,{...a,x:5}),false);});
test('layout import reconstructs only valid fields',()=>{const src={format:'house-studio-3d',version:1,name:'Test',preset:'everyday',items:preset('everyday')};assert.equal(validateLayout(src).items.length,src.items.length);assert.throws(()=>validateLayout({}));assert.throws(()=>validateLayout({...src,items:[...src.items,src.items[0]]}));assert.throws(()=>validateLayout({...src,items:[{...src.items[0],x:Infinity}]}));assert.throws(()=>validateLayout({...src,items:[{...src.items[0],color:'url(evil)'}]}));assert.throws(()=>validateLayout({...src,items:[{...src.items[0],type:'unknown'}]}));});
test('all 29 catalogue models contain finite geometry',()=>{assert.equal(CATALOG.length,29);for(const d of CATALOG){const model=furnitureModel(item(d.type,0,0));model.updateMatrixWorld(true);const bounds=new T.Box3().setFromObject(model);assert.ok(!bounds.isEmpty(),d.type);for(const n of [...bounds.min.toArray(),...bounds.max.toArray()])assert.ok(Number.isFinite(n),d.type);assert.ok(bounds.getSize(new T.Vector3()).y>0,d.type);disposeModel(model);}});
test('house geometry and six-part person have correct scale',()=>{const scene=new T.Scene(),house=buildHouse(scene),person=makePerson(scene);scene.updateMatrixWorld(true);const all=new T.Box3().setFromObject(house.structure);assert.ok(all.min.x<=-3.75+.03);assert.ok(all.max.x>=2.25);let meshCount=0;person.root.traverse(o=>{if(o.isMesh)meshCount++;});assert.equal(meshCount,6);const bounds=new T.Box3().setFromObject(person.root);assert.ok(Math.abs(bounds.getSize(new T.Vector3()).y-1.70)<.005);assert.ok(bounds.getSize(new T.Vector3()).x<personRadius(1.7)*2);});
test('sofa collision footprint scales with actual open geometry',()=>{const o=item('sofabed',0,0,0,{open:true,d:1.1}),p=pieces(o)[0],model=furnitureModel(o),bounds=new T.Box3().setFromObject(model);assert.ok(Math.abs((p.z-p.d/2)-bounds.min.z)<.015);assert.ok(Math.abs((p.z+p.d/2)-bounds.max.z)<.02);disposeModel(model);});
test('offline entry references only bundled local files',()=>{const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');const refs=[...html.matchAll(/(?:src|href)="([^"]+)"/g)].map(m=>m[1]).filter(s=>s!=='#'&&!s.startsWith('data:'));for(const ref of refs){assert.ok(!/^https?:/.test(ref),ref);assert.ok(existsSync(new URL('../'+ref,import.meta.url)),ref);}assert.ok(!html.includes('type="module"'));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(new Set(ids).size,ids.length,'duplicate HTML IDs');});
