import test from 'node:test';
import assert from 'node:assert/strict';
import { WALLS,DOOR_ZONES,setStructure,pointBlocked,surfaceHeight,findPath,validateLayout,item,preset } from '../src/core.js';
const example=()=>({bounds:{left:-2.25,right:2.25,back:-2.375,front:2.375},bathroom:{x:-3,z:-.875,w:1.5,d:3},balcony:{depth:1},openings:[{id:'front-door',kind:'door',side:'front',at:0,w:2,h:2,sill:0},{id:'rear-door',kind:'door',side:'back',at:1.65,w:.8,h:2,sill:0},{id:'bath-access',kind:'door',side:'left',at:.05,w:.8,h:2,sill:0},{id:'bath-inner',kind:'door',side:'bath-right',at:.05,w:.8,h:2,sill:0}],partitions:[],colors:{wall:'#eeeae0',floor:'#d2b991',foundation:'#b2b4a7',bathWall:'#e4e8e4',bathFloor:'#d8dbd1',roof:'#454d48',bathRoof:'#525e55',balcony:'#a58b67',rail:'#866e50',door:'#9a8262',window:'#9dbab6',frame:'#38433f',trim:'#d8d3c8',garden:'#9ba990'}});
test('moving exterior wall resizes the walkable raised floor and navigational wall',()=>{const s=example();setStructure(s);assert.equal(surfaceHeight(2.7,0),.025);s.bounds.right=3;setStructure(s);assert.equal(surfaceHeight(2.7,0),.38);assert.equal(pointBlocked(3,0,WALLS,.10),true);assert.equal(pointBlocked(2.25,0,WALLS,.10),false);});
test('moving front door relocates its actual collision opening',()=>{const s=example();setStructure(s);assert.equal(pointBlocked(-.5,s.bounds.front,WALLS,.1),false);s.openings[0].at=-1;setStructure(s);assert.equal(pointBlocked(-1.5,s.bounds.front,WALLS,.1),false);assert.equal(pointBlocked(.3,s.bounds.front,WALLS,.1),true);assert.equal(DOOR_ZONES.find(z=>z.name==='front-door').x,-1);});
test('bathroom shell and floor follow its position, including a relocated entry',()=>{const s=example();s.bathroom.x=-4;s.bathroom.z=-1.25;s.openings[3].at=-1.25;setStructure(s);assert.equal(surfaceHeight(-4,-1.25),.38);assert.equal(surfaceHeight(-3,0),.025);assert.equal(pointBlocked(-3.25,-1.25,WALLS,.1),false);assert.equal(pointBlocked(-3.25,-.1,WALLS,.1),true);});
test('partitions block routes at their new position',()=>{const s=example();s.partitions.push({id:'wall-extra',x:0,z:0,w:4,d:.15,h:3,rot:0,color:'#eeeae0'});setStructure(s);assert.equal(pointBlocked(0,0,WALLS,.1),true);s.partitions[0].z=-1;setStructure(s);assert.equal(pointBlocked(0,0,WALLS,.1),false);assert.equal(pointBlocked(0,-1,WALLS,.1),true);});
test('structure JSON remains portable, rejects invalid colors and duplicate opening IDs',()=>{const s=example(),doc={format:'house-studio-3d',version:1,items:preset('everyday'),name:'Test',structure:s};assert.equal(validateLayout(doc).structure.bounds.right,2.25);assert.throws(()=>validateLayout({...doc,structure:{...s,colors:{...s.colors,wall:'javascript:evil'}}}));assert.throws(()=>validateLayout({...doc,structure:{...s,openings:[...s.openings,s.openings[0]]}}));});
