import * as T from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { FLOOR, CATALOG, PRESETS, definitions, preset, item, uid, itemWarnings, worldPoint, localPoint, pieces, navObstacles, pointBlocked, findPath, destination, surfaceHeight, validateLayout, overlap, WALLS, personRadius } from './core.js';
import { box, mat, buildHouse, furnitureModel, makePerson, disposeModel } from './models.js';
import { icon, fillIcons } from './icons.js';
import { DEFAULT_STRUCTURE, cloneStructure, makeArchitecture, removeArchitecture, wallSpec, SIDES, structuralIssues } from './architecture.js';

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
fillIcons();
let toastTimer;function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
let storageOkay=true;function readStorage(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}}function writeStorage(key,value){try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{storageOkay=false;$('#saveStatus').textContent='Export JSON to save';return false;}}
let state={format:'house-studio-3d',version:1,name:'Everyday studio',preset:'everyday',items:preset('everyday'),structure:cloneStructure()};
try{const previous=readStorage('house-studio-autosave-v1',null);if(previous)state=validateLayout(previous);}catch{/* Keep a valid default if old local data is corrupted. */}
state.structure ||= cloneStructure();
let mode='explore',selectedId=null,snap=true,wallMode='cutaway',showRoof=false,lighting='day',measureMode=false,follow=false,autoOrbit=false;
let history=[],future=[],models=new Map(),drag=null,lastPointer=null,cameraTransition=null,currentView='iso',selectedStructure='floor',buildDrag=null;
const scene=new T.Scene();scene.background=new T.Color('#e7ede3');scene.fog=new T.Fog('#e7ede3',26,65);
const host=$('#canvasHost');let renderer;
try{renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});}catch(err){$('#loading').innerHTML='<b>3D rendering is unavailable.</b><small>Use Chrome or Edge with hardware acceleration enabled.</small><small>Your saved layouts have not been changed.</small>';throw err;}
renderer.setPixelRatio(Math.min(devicePixelRatio,1.65));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=T.SRGBColorSpace;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','House scene. Use mouse to orbit and zoom; select furniture in Decorate.');
const perspective=new T.PerspectiveCamera(39,1,.05,180),ortho=new T.OrthographicCamera(-7,7,7,-7,.05,100);let camera=perspective;perspective.position.set(8.2,9.4,12.7);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(-.58,.65,-.15);controls.enableDamping=true;controls.dampingFactor=.10;controls.minDistance=2;controls.maxDistance=28;controls.maxPolarAngle=Math.PI*.485;controls.enablePan=true;controls.zoomToCursor=true;
const hemi=new T.HemisphereLight('#f5faf1','#828d70',2.2);scene.add(hemi);const sun=new T.DirectionalLight('#fff3d8',3.2);sun.position.set(-6,10,8);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-9,right:9,top:9,bottom:-9,near:.5,far:40});sun.shadow.normalBias=.035;sun.shadow.bias=-.0001;sun.shadow.radius=4;scene.add(sun);const fill=new T.DirectionalLight('#dcebea',.55);fill.position.set(6,4,-4);scene.add(fill);
let house=makeArchitecture(scene,state.structure),furnitureGroup=new T.Group();scene.add(furnitureGroup);const blocky=makePerson(scene);blocky.root.visible=false;
let structureSnapshot=JSON.stringify(state.structure);
const grid=new T.GridHelper(12,120,'#9baea0','#c4cfc0');grid.position.y=FLOOR+.008;grid.material.transparent=true;grid.material.opacity=.18;grid.visible=false;scene.add(grid);
const selection=new T.Box3Helper(new T.Box3(),0x4b7d61);scene.add(selection);selection.visible=false;
const routeGroup=new T.Group(),dimensionGroup=new T.Group(),measureGroup=new T.Group(),clearanceGroup=new T.Group();scene.add(routeGroup,dimensionGroup,measureGroup,clearanceGroup);dimensionGroup.visible=false;clearanceGroup.visible=false;
let walking={path:[],index:0,action:null,phase:'idle',elapsed:0,transition:null,routine:false,routineIndex:0,wait:0};
const personPos=()=>({x:blocky.root.position.x,z:blocky.root.position.z});let personHeight=1.70;

function rebuild(){
 for(const m of models.values()){furnitureGroup.remove(m);disposeModel(m);}models.clear();for(const o of state.items){const m=furnitureModel(o);models.set(o.id,m);furnitureGroup.add(m);}updateSelection();updateLabels();
}
function rebuildStructure(){const next=JSON.stringify(state.structure);if(next===structureSnapshot)return;structureSnapshot=next;removeArchitecture(scene,house);house=makeArchitecture(scene,state.structure);applyVisibility();updateLights();house.garden.visible=$('#gardenToggle').checked;house.base.material.color.set(scene.background);updateDimensions();renderBuild();}
function save(){if(writeStorage('house-studio-autosave-v1',state))$('#saveStatus').textContent='Saved on this device';}
function checkpoint(){history.push(JSON.stringify(state));if(history.length>45)history.shift();future=[];updateHistory();}
function updateHistory(){$('#undoBtn').disabled=!history.length;$('#redoBtn').disabled=!future.length;}
function commit(rebuildAll=true){if(rebuildAll)rebuild();else{updateSelection();updateLabels();}rebuildStructure();save();updateHistory();if(selectedId)renderInspector();$('#pathResults').innerHTML='';stopWalking(false);}
function undo(){if(!history.length)return;future.push(JSON.stringify(state));state=JSON.parse(history.pop());state.structure ||= cloneStructure();selectedId=null;rebuild();rebuildStructure();save();updateHistory();stopWalking(false);toast('Change undone.');}
function redo(){if(!future.length)return;history.push(JSON.stringify(state));state=JSON.parse(future.pop());state.structure ||= cloneStructure();selectedId=null;rebuild();rebuildStructure();save();updateHistory();stopWalking(false);toast('Change restored.');}
function updateLabels(){$('#layoutLabel').textContent=state.name;$('#sceneSubline').textContent=PRESETS.find(p=>p.id===state.preset)?.description||'Your furniture. Your arrangement.';const s=state.structure;if(s){$('#mainDimensions').textContent=`${(s.bounds.right-s.bounds.left).toFixed(2)} × ${(s.bounds.front-s.bounds.back).toFixed(2)}`;$('#bathDimensions').textContent=`${s.bathroom.w.toFixed(2)} × ${s.bathroom.d.toFixed(2)}`;$('#balconyDimensions').textContent=`${(s.bounds.right-s.bounds.left).toFixed(2)} × ${s.balcony.depth.toFixed(2)} m`;}$$('[data-preset]').forEach(el=>el.classList.toggle('active',el.dataset.preset===state.preset));}
function applyPreset(id){checkpoint();state={...state,preset:id,name:PRESETS.find(p=>p.id===id).name,items:preset(id)};selectedId=null;commit();resetPerson();toast('Furniture layout loaded; your edited house structure was kept.');}
function setMode(value){mode=value;document.body.classList.remove('mode-explore','mode-build','mode-decorate','mode-simulate');document.body.classList.add('mode-'+value);$$('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===value));for(const m of ['explore','build','decorate','simulate'])$('#'+m+'Panel').hidden=m!==value;grid.visible=(value==='decorate'||value==='build')&&snap;clearanceGroup.visible=value==='decorate';blocky.root.visible=value==='simulate';if(value!=='decorate'){selectedId=null;renderInspector();updateSelection();}if(value==='build'){showRoof=false;wallMode='cutaway';$('#wallSelect').value=wallMode;applyVisibility();renderBuild();}if(value==='decorate'){showRoof=false;applyVisibility();renderCatalog();}if(value==='simulate'){showRoof=false;wallMode='cutaway';$('#wallSelect').value=wallMode;applyVisibility();ensurePersonFree();}else stopWalking(false);$('#inputHint').textContent=value==='build'?'Click structural elements to select · drag to reposition · use panel for exact sizes':value==='decorate'?'Drag furniture to move · R rotate · Arrow keys nudge · Delete remove':value==='simulate'?'Click the floor to walk · Drag empty space to orbit · Scroll to zoom':'Drag to orbit · Scroll to zoom · Right-drag to pan';}

function resize(){const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);perspective.aspect=w/h;perspective.updateProjectionMatrix();const span=6.15;ortho.left=-span*w/h;ortho.right=span*w/h;ortho.top=span;ortho.bottom=-span;ortho.updateProjectionMatrix();}
new ResizeObserver(resize).observe(host);
function view(type){autoOrbit=false;currentView=type;$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===type));$('#cameraTourBtn').innerHTML=icon('play');const target=new T.Vector3(-.60,.60,-.18);if(type==='top'){camera=ortho;camera.position.set(-.6,18,-.179);camera.up.set(0,0,-1);camera.lookAt(target);controls.object=camera;controls.target.copy(target);controls.enableRotate=false;ortho.zoom=1;ortho.updateProjectionMatrix();showRoof=false;wallMode='hidden';$('#wallSelect').value=wallMode;applyVisibility();cameraTransition=null;}else{camera=perspective;controls.object=camera;controls.enableRotate=true;camera.up.set(0,1,0);const positions={iso:[8.2,9.4,12.7],front:[0,2.5,12],back:[0,3,-12]};cameraTransition={from:camera.position.clone(),to:new T.Vector3(...positions[type]),targetFrom:controls.target.clone(),targetTo:target,t:0};if(type==='front'||type==='back'){wallMode='full';showRoof=true;$('#wallSelect').value=wallMode;applyVisibility();}else{wallMode='cutaway';showRoof=false;$('#wallSelect').value=wallMode;applyVisibility();}}resize();controls.update();}
function applyVisibility(){house.full.visible=wallMode==='full';house.cut.visible=wallMode==='cutaway';house.roof.visible=showRoof;house.doors.visible=wallMode!=='hidden';house.lightsGroup.visible=wallMode==='full';$('#roofBtn span').textContent=showRoof?'Roof on':'Roof off';$('#roofBtn').classList.toggle('active',showRoof);$('#viewLabel').textContent=currentView==='top'?'FLOOR PLAN':wallMode==='full'?'EXTERIOR':wallMode==='hidden'?'OPEN PLAN':'CUTAWAY';}
function setLight(value){lighting=value;const configs={day:{bg:'#e7ede3',sun:'#fff3dc',intensity:3.2,hemi:2.2,pos:[-6,10,8],exposure:1.12},sunset:{bg:'#decbb4',sun:'#ffb56c',intensity:3.0,hemi:1.35,pos:[-9,3.4,5],exposure:1.12},night:{bg:'#1a2e32',sun:'#b9cee3',intensity:.6,hemi:.55,pos:[5,8,-7],exposure:1.15}};const c=configs[value];scene.background.set(c.bg);scene.fog.color.set(c.bg);house.base.material.color.set(c.bg);sun.color.set(c.sun);sun.intensity=c.intensity;sun.position.set(...c.pos);hemi.intensity=c.hemi;renderer.toneMappingExposure=c.exposure;document.body.classList.toggle('night',value==='night');$$('[data-light]').forEach(b=>b.classList.toggle('active',b.dataset.light===value));updateLights();}
function updateLights(){house.lights.forEach(l=>l.intensity=$('#lightsToggle').checked?(lighting==='night'?7:lighting==='sunset'?4:1.3):0);}

// Catalogue images are real renders of the exact local models, not remote assets.
const thumbCache=new Map();let thumbRenderer;
function thumbnail(type){if(thumbCache.has(type))return thumbCache.get(type);try{if(!thumbRenderer){thumbRenderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});thumbRenderer.setSize(240,170);thumbRenderer.setPixelRatio(1);thumbRenderer.toneMapping=T.ACESFilmicToneMapping;thumbRenderer.toneMappingExposure=1.25;}const ts=new T.Scene();ts.background=new T.Color('#edf1e9');ts.add(new T.HemisphereLight('#fff8e9','#b0b7a1',2.7));const light=new T.DirectionalLight('#fff5de',3);light.position.set(-3,5,4);ts.add(light);const o=item(type,0,0),m=furnitureModel(o);m.position.set(0,0,0);ts.add(m);const b=new T.Box3().setFromObject(m),center=b.getCenter(new T.Vector3()),sz=b.getSize(new T.Vector3()),len=Math.max(sz.x,sz.y,sz.z);const c=new T.PerspectiveCamera(37,240/170,.01,100);c.position.copy(center).add(new T.Vector3(1.5,1.25,1.8).multiplyScalar(len*.83));c.lookAt(center);thumbRenderer.render(ts,c);const uri=thumbRenderer.domElement.toDataURL();thumbCache.set(type,uri);disposeModel(m);return uri;}catch{return '';}}
function renderPresets(){$('#presetCards').innerHTML=PRESETS.map((p,i)=>`<button class="preset-card ${state.preset===p.id?'active':''}" data-preset="${p.id}"><img alt="" src="${thumbnail(['bed5','loft35','sofabed'][i])}"><span><b>${p.name}</b><small>${p.subtitle}</small></span></button>`).join('');$$('[data-preset]').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));}
let category='All';const categories=['All',...new Set(CATALOG.map(o=>o.cat))];
function renderCatalog(){const q=$('#searchInput').value.toLowerCase();const list=CATALOG.filter(o=>(category==='All'||o.cat===category)&&o.name.toLowerCase().includes(q));$('#catalogCount').textContent=`${list.length} ITEMS`;$('#categoryTabs').innerHTML=categories.map(c=>`<button class="${c===category?'active':''}" data-category="${c}">${c}</button>`).join('');$('#catalog').innerHTML=list.map(o=>`<button class="catalog-item" data-add="${o.type}"><img alt="" src="${thumbnail(o.type)}"><span class="add-symbol">+</span><b>${o.name}</b><small>${o.w.toFixed(2)} × ${o.d.toFixed(2)} m</small></button>`).join('')||'<p class="empty-copy">No matching furniture.</p>';$$('[data-add]').forEach(b=>b.onclick=()=>addItem(b.dataset.add));$$('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category;renderCatalog();});}
function addItem(type){if(state.items.length>=180){toast('This layout has reached the 180-item limit.');return;}checkpoint();let o=item(type,0,.5),placed=false;const candidates=[];for(let z=1.5;z>-2;z-=.25)for(let x=-1.8;x<2;x+=.25)candidates.push({x,z});for(const p of candidates){o.x=Math.round(p.x*10)/10;o.z=Math.round(p.z*10)/10;if(!itemWarnings(o,state.items).some(t=>!t.startsWith('Loft:'))){placed=true;break;}}if(!placed){o.x=3.25;o.z=.6;toast('Added beside the house. Drag it into position.');}else toast(`${definitions[type].name} added.`);state.items.push(o);state.preset='custom';state.name='My little house';selectedId=o.id;commit();}
function selected(){return state.items.find(o=>o.id===selectedId);}
function updateSelection(){const m=models.get(selectedId);selection.visible=!!m&&mode==='decorate';if(m){m.updateMatrixWorld(true);selection.box.setFromObject(m);selection.material.color.set(itemWarnings(selected(),state.items).some(t=>t.startsWith('Overlaps'))?'#d06c51':'#3f7c59');}$('#inspector').hidden=!m||mode!=='decorate';}
function select(id){selectedId=id;updateSelection();renderInspector();}
function changeSelected(mutator){const o=selected();if(!o)return;checkpoint();mutator(o);state.preset='custom';commit();}
function renderInspector(){const o=selected(),panel=$('#inspector');panel.hidden=!o||mode!=='decorate';if(!o)return;const def=definitions[o.type],warnings=itemWarnings(o,state.items);panel.innerHTML=`<div class="inspector-head"><div><span class="eyebrow">SELECTED OBJECT</span><h3>${def.name}</h3></div><button id="closeInspector" class="icon-btn" aria-label="Deselect">${icon('close')}</button></div><div class="row"><label class="field-label">X · metres<input id="objectX" type="number" min="-6" max="6" step=".1" value="${o.x.toFixed(2)}"></label><label class="field-label">Z · metres<input id="objectZ" type="number" min="-6" max="6" step=".1" value="${o.z.toFixed(2)}"></label></div><div class="row"><label class="field-label">Width<input id="objectW" type="number" min=".1" max="4" step=".05" value="${o.w.toFixed(2)}"></label><label class="field-label">Depth<input id="objectD" type="number" min=".1" max="4" step=".05" value="${o.d.toFixed(2)}"></label><label class="field-label">Height<input id="objectH" type="number" min=".01" max="3" step=".05" value="${o.h.toFixed(2)}"></label></div><label class="field-label">Rotation · degrees<input id="objectRotation" type="number" step="15" value="${Math.round(o.rot*180/Math.PI)}"></label><div class="swatches">${['#d9d7c8','#c6ac83','#a7b7a0','#425956','#343b3b','#d7a681','#eeeeea'].map(c=>`<button class="${o.color===c?'active':''}" style="background:${c}" data-color="${c}" title="Colour ${c}" aria-label="Colour ${c}"></button>`).join('')}<input id="customColor" type="color" value="${o.color}" aria-label="Custom colour" style="width:27px;height:27px;border:0;padding:0"></div>${def.kind==='sofabed'?`<button id="sofaToggle" class="btn wide secondary">${o.open?'Fold into sofa':'Unfold into bed'}</button>`:''}<div class="button-row"><button id="rotateObject" class="btn secondary" title="Rotate 90 degrees">${icon('rotate')}90°</button><button id="duplicateObject" class="icon-btn" title="Duplicate" aria-label="Duplicate">${icon('copy')}</button><button id="deleteObject" class="icon-btn danger" title="Delete" aria-label="Delete">${icon('trash')}</button></div>${warnings.length?warnings.map(t=>`<p class="warning">${t}</p>`).join(''):'<p class="good">✓ No object or wall overlap detected.</p>'}<p>Dimensions include the model frame. Resize to match your actual furniture. Arrow keys nudge by ${snap?'10':'2'} cm.</p>`;
 $('#closeInspector').onclick=()=>select(null);for(const [id,k,min,max] of [['objectX','x',-6,6],['objectZ','z',-6,6],['objectW','w',.1,4],['objectD','d',.1,4],['objectH','h',.01,3]])$('#'+id).onchange=e=>{const v=Number(e.target.value);if(!Number.isFinite(v)||v<min||v>max){toast(`Use a value from ${min} to ${max}.`);renderInspector();return;}changeSelected(o=>o[k]=v);};$('#objectRotation').onchange=e=>{const v=Number(e.target.value);if(Number.isFinite(v))changeSelected(o=>o.rot=((v%360)+360)%360*Math.PI/180);};$$('[data-color]').forEach(b=>b.onclick=()=>changeSelected(o=>o.color=b.dataset.color));$('#customColor').onchange=e=>changeSelected(o=>o.color=e.target.value);$('#rotateObject').onclick=()=>rotateItem();$('#duplicateObject').onclick=duplicateItem;$('#deleteObject').onclick=deleteItem;if($('#sofaToggle'))$('#sofaToggle').onclick=()=>changeSelected(o=>o.open=!o.open);
}
function rotateItem(){changeSelected(o=>o.rot=(o.rot+Math.PI/2)%(Math.PI*2));}
function duplicateItem(){if(!selected()||state.items.length>=180)return;checkpoint();const o={...selected(),id:uid(),x:Math.min(6,selected().x+.35),z:Math.min(6,selected().z+.35)};state.items.push(o);selectedId=o.id;commit();toast('Duplicated. Move the new item into place.');}
function deleteItem(){if(!selectedId)return;checkpoint();state.items=state.items.filter(o=>o.id!==selectedId);selectedId=null;commit();toast('Object removed. Undo is available.');}

const raycaster=new T.Raycaster(),mouse=new T.Vector2(),floorPlane=new T.Plane(new T.Vector3(0,1,0),-FLOOR),groundPoint=new T.Vector3();
function ray(e){const r=renderer.domElement.getBoundingClientRect();mouse.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(mouse,camera);}
function pointAt(e){ray(e);return raycaster.ray.intersectPlane(floorPlane,groundPoint)?.clone();}
function pick(e){ray(e);const hits=raycaster.intersectObjects([...models.values()],true);for(const h of hits){let o=h.object;while(o&&!o.userData.itemId)o=o.parent;if(o)return o.userData.itemId;}return null;}
renderer.domElement.addEventListener('pointerdown',e=>{if(e.button!==0)return;lastPointer={x:e.clientX,y:e.clientY,id:e.pointerId};if(mode==='decorate'&&!measureMode){const id=pick(e);if(id){select(id);const p=pointAt(e),o=selected();if(p){drag={id,dx:o.x-p.x,dz:o.z-p.z,started:false};controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);}return;}}},true);
renderer.domElement.addEventListener('pointermove',e=>{if(!drag||!lastPointer)return;if(Math.hypot(e.clientX-lastPointer.x,e.clientY-lastPointer.y)<4&&!drag.started)return;if(!drag.started){checkpoint();drag.started=true;stopWalking(false);}const p=pointAt(e),o=selected();if(!p||!o)return;const step=snap?.1:.01;o.x=Math.max(-6,Math.min(6,Math.round((p.x+drag.dx)/step)*step));o.z=Math.max(-6,Math.min(6,Math.round((p.z+drag.dz)/step)*step));const m=models.get(o.id);m.position.set(o.x,surfaceHeight(o.x,o.z)+.015,o.z);updateSelection();});
renderer.domElement.addEventListener('pointerup',e=>{if(e.button!==0)return;const moved=lastPointer&&Math.hypot(e.clientX-lastPointer.x,e.clientY-lastPointer.y)>5;if(drag){if(drag.started){state.preset='custom';commit(false);}drag=null;controls.enabled=true;lastPointer=null;return;}if(!moved&&lastPointer){const p=pointAt(e);if(measureMode&&p)addMeasurement(p);else if(mode==='simulate'&&p)walkToPoint({x:p.x,z:p.z});else if(mode==='decorate')select(pick(e));}lastPointer=null;});
renderer.domElement.addEventListener('pointercancel',()=>{if(drag?.started)commit(false);drag=null;controls.enabled=true;lastPointer=null;});
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return;}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return;}if(e.key==='Escape'){select(null);if(document.body.classList.contains('presentation'))present(false);if(measureMode)toggleMeasure();return;}if(mode!=='decorate'||!selected())return;if(e.key.toLowerCase()==='r')rotateItem();if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();deleteItem();}if(e.key.startsWith('Arrow')){e.preventDefault();const step=snap?.1:.02;changeSelected(o=>{if(e.key==='ArrowLeft')o.x=Math.max(-6,o.x-step);if(e.key==='ArrowRight')o.x=Math.min(6,o.x+step);if(e.key==='ArrowUp')o.z=Math.max(-6,o.z-step);if(e.key==='ArrowDown')o.z=Math.min(6,o.z+step);});}});

function emptyGroup(g){while(g.children.length){const c=g.children[0];g.remove(c);if(c.userData.disposable){c.geometry?.dispose();c.material?.map?.dispose();c.material?.dispose();}}}
function line(group,points,color='#58845e',dashed=false){const geometry=new T.BufferGeometry().setFromPoints(points.map(p=>new T.Vector3(...p)));const material=dashed?new T.LineDashedMaterial({color,dashSize:.10,gapSize:.07,depthTest:false}):new T.LineBasicMaterial({color,depthTest:false});const m=new T.Line(geometry,material);m.userData.disposable=true;m.renderOrder=10;if(dashed)m.computeLineDistances();group.add(m);return m;}
function label(group,text,x,y,z,scale=1){const c=document.createElement('canvas');c.width=512;c.height=128;const ctx=c.getContext('2d');ctx.fillStyle='#f9fcf5';ctx.beginPath();ctx.roundRect(3,5,506,116,22);ctx.fill();ctx.fillStyle='#294b3d';ctx.font='500 49px Arial';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(text,256,65);const tex=new T.CanvasTexture(c);tex.colorSpace=T.SRGBColorSpace;const m=new T.Sprite(new T.SpriteMaterial({map:tex,depthTest:false,transparent:true}));m.position.set(x,y,z);m.scale.set(1.2*scale,.30*scale,1);m.renderOrder=20;m.userData.disposable=true;group.add(m);return m;}
function dimension(a,b,text){line(dimensionGroup,[a,b]);for(const p of [a,b])line(dimensionGroup,[[p[0]-.06,p[1],p[2]-.06],[p[0]+.06,p[1],p[2]+.06]]);label(dimensionGroup,text,(a[0]+b[0])/2,.5,(a[2]+b[2])/2,.85);}
function updateDimensions(){emptyGroup(dimensionGroup);emptyGroup(clearanceGroup);const s=state.structure,b=s.bounds,q=s.bathroom;
 dimension([b.left,.43,b.front+.88],[b.right,.43,b.front+.88],`${(b.right-b.left).toFixed(2)} m`);
 dimension([b.right+.70,.43,b.back],[b.right+.70,.43,b.front],`${(b.front-b.back).toFixed(2)} m`);
 dimension([q.x-q.w/2-.36,.43,q.z-q.d/2],[q.x-q.w/2-.36,.43,q.z+q.d/2],`${q.d.toFixed(2)} m`);
 dimension([q.x-q.w/2,.43,q.z+q.d/2+.28],[q.x+q.w/2,.43,q.z+q.d/2+.28],`${q.w.toFixed(2)} m`);
 dimension([b.left,.43,b.back-s.balcony.depth-.35],[b.right,.43,b.back-s.balcony.depth-.35],`${(b.right-b.left).toFixed(2)} m balcony`);
 for(const o of s.openings.filter(o=>o.kind==='door')){const w=wallSpec(s,o.side),x=w.axis==='x'?o.at:w.fixed,z=w.axis==='x'?w.fixed:o.at,ww=w.axis==='x'?o.w:.58,dd=w.axis==='x'?.58:o.w;line(clearanceGroup,[[x-ww/2,FLOOR+.019,z-dd/2],[x+ww/2,FLOOR+.019,z-dd/2],[x+ww/2,FLOOR+.019,z+dd/2],[x-ww/2,FLOOR+.019,z+dd/2],[x-ww/2,FLOOR+.019,z-dd/2]],'#bb9561',true);}
}
let measurePoints=[];function toggleMeasure(){measureMode=!measureMode;$('#measureBtn').classList.toggle('active',measureMode);$('#measureReadout').hidden=!measureMode;measurePoints=[];emptyGroup(measureGroup);$('#measureReadout').textContent='Click two points on the floor.';renderer.domElement.style.cursor=measureMode?'crosshair':'';}
function addMeasurement(p){if(measurePoints.length===2){measurePoints=[];emptyGroup(measureGroup);}p.y=FLOOR+.035;measurePoints.push(p);const dot=new T.Mesh(new T.SphereGeometry(.035,12,8),new T.MeshBasicMaterial({color:'#285747',depthTest:false}));dot.position.copy(p);dot.userData.disposable=true;measureGroup.add(dot);if(measurePoints.length===2){const [a,b]=measurePoints,distance=a.distanceTo(b);line(measureGroup,[a.toArray(),b.toArray()],'#285747');label(measureGroup,distance.toFixed(2)+' m',(a.x+b.x)/2,.52,(a.z+b.z)/2);$('#measureReadout').textContent=`${distance.toFixed(2)} m floor distance · click to start again`;}}
updateDimensions();

function setPersonStatus(text,detail){$('#personStatus').textContent=text;$('#personDetail').textContent=detail||'Click the floor to walk somewhere.';}
function stopWalking(show=true){const old=walking.action;if(old?.item&&walking.phase!=='walking'&&walking.phase!=='idle')blocky.root.position.set(old.x,surfaceHeight(old.x,old.z)+.015,old.z);walking={path:[],index:0,action:null,phase:'idle',elapsed:0,transition:null,routine:false,routineIndex:0,wait:0};emptyGroup(routeGroup);blocky.reset();const p=personPos();blocky.root.position.y=surfaceHeight(p.x,p.z)+.015;if(show){ensurePersonFree();setPersonStatus('Ready to explore');}else if(mode==='simulate'){ensurePersonFree();setPersonStatus('Ready to explore');}}
function resetPerson(){stopWalking(false);blocky.root.position.set(0,FLOOR+.015,1.3);blocky.root.rotation.y=0;ensurePersonFree();setPersonStatus('Ready to explore');}
function ensurePersonFree(){const p=personPos(),obs=navObstacles(state.items,personHeight),r=personRadius(personHeight);if(!pointBlocked(p.x,p.z,obs,r))return;const candidates=[{x:0,z:1.3},{x:0,z:2},{x:0,z:3.5}];for(let z=-2;z<2;z+=.2)for(let x=-2;x<2;x+=.2)candidates.push({x,z});const q=candidates.find(q=>!pointBlocked(q.x,q.z,obs,r));if(q){blocky.root.position.set(q.x,surfaceHeight(q.x,q.z)+.015,q.z);}}
function drawRoute(path){emptyGroup(routeGroup);routeGroup.visible=$('#pathToggle').checked;if(!path?.length)return;line(routeGroup,path.map(p=>[p.x,surfaceHeight(p.x,p.z)+.035,p.z]),'#397b5e',true);const p=path[path.length-1];const ring=new T.Mesh(new T.RingGeometry(.12,.16,32),new T.MeshBasicMaterial({color:'#4d8d68',side:T.DoubleSide,depthTest:false}));ring.rotation.x=-Math.PI/2;ring.position.set(p.x,surfaceHeight(p.x,p.z)+.04,p.z);ring.userData.disposable=true;routeGroup.add(ring);}
function startPath(path,action=null,keepRoutine=false){const routine=walking.routine,routineIndex=walking.routineIndex;blocky.reset();walking={path,index:0,action,phase:'walking',elapsed:0,transition:null,routine:keepRoutine&&routine,routineIndex,wait:0};drawRoute(path);setPersonStatus('Walking…',action?.label||'Finding a little breathing room.');}
function walkToPoint(point){stopWalking(false);ensurePersonFree();const path=findPath(personPos(),point,state.items,personHeight);if(!path){toast('No walkable route there. Try a clear floor area or move the blocking furniture.');setPersonStatus('That spot is blocked','Try another spot, or make more room.');return;}startPath(path);}
function action(name,keepRoutine=false){
 if(name==='tour'){stopWalking(false);walking.routine=true;walking.routineIndex=0;action('desk',true);return;}
 if(!keepRoutine)stopWalking(false);else{blocky.reset();ensurePersonFree();}
 if(name==='bed'){const sofa=state.items.find(o=>definitions[o.type].kind==='sofabed');if(sofa&&!sofa.open&&!state.items.some(o=>['bed','loft'].includes(definitions[o.type].kind))){checkpoint();sofa.open=true;rebuild();save();updateHistory();}}
 const options=destination(name,state.items);if(!options.length){toast(`Add ${name==='bed'?'a bed':'a desk'} first.`);setPersonStatus('Destination not available');walking.routine=false;return;}
 let chosen=null,path=null;for(const candidate of options){const p=findPath(personPos(),candidate,state.items,personHeight);if(p&&(!path||p.length<path.length)){chosen=candidate;path=p;}}
 if(!path){toast('Route blocked. Move furniture, resize it, or check the door clearances.');setPersonStatus('Cannot reach '+name,'The walking route is blocked.');walking.routine=false;return;}startPath(path,chosen,keepRoutine);
}
function arrive(){walking.phase='rest';walking.elapsed=0;walking.path=[];emptyGroup(routeGroup);const a=walking.action;if(!a){setPersonStatus('Arrived');return;}if(a.pose==='sleep'&&a.item){const o=state.items.find(i=>i.id===a.item.id);if(!o){stopWalking();return;}const kind=definitions[o.type].kind;const center=worldPoint(o,0,kind==='sofabed'?.65*o.d/definitions[o.type].d:0);const top=kind==='loft'?o.h*1.88/2.25:kind==='sofabed'?o.h*.45/.84:o.h*.55/definitions[o.type].h;walking.phase='settle';walking.transition={from:blocky.root.position.clone(),to:new T.Vector3(center.x,surfaceHeight(center.x,center.z)+top+.10,center.z),yaw:o.rot,pose:'sleep',loft:kind==='loft',duration:kind==='loft'?2.8:1.1};setPersonStatus(kind==='loft'?'Climbing up…':'Getting comfortable…','A simplified pose transition; not an ergonomic test.');}else if(a.pose==='sit'&&a.item){const o=a.item;walking.phase='settle';walking.transition={from:blocky.root.position.clone(),to:new T.Vector3(o.x,surfaceHeight(o.x,o.z)+.015,o.z),yaw:o.rot,pose:'sit',duration:.85};setPersonStatus('Taking a seat…');}else{setPersonStatus(a.label);walking.wait=0;}}
function updatePerson(dt,time){
 const g=blocky.root;g.scale.setScalar(personHeight/1.70);
 if(walking.phase==='walking'){
  let distance=dt*.92;while(distance>0&&walking.index<walking.path.length){const p=walking.path[walking.index],dx=p.x-g.position.x,dz=p.z-g.position.z,dist=Math.hypot(dx,dz);if(dist<.001){walking.index++;continue;}g.rotation.y=Math.atan2(dx,dz);const step=Math.min(distance,dist);g.position.x+=dx/dist*step;g.position.z+=dz/dist*step;distance-=step;if(step>=dist-.0001)walking.index++;}
  g.position.y=surfaceHeight(g.position.x,g.position.z)+.015;blocky.legs[0].rotation.x=Math.sin(time*9)*.32;blocky.legs[1].rotation.x=-Math.sin(time*9)*.32;blocky.arms[0].rotation.x=-Math.sin(time*9)*.31;blocky.arms[1].rotation.x=Math.sin(time*9)*.31;blocky.body.position.y=Math.abs(Math.sin(time*9))*.018;
  if(walking.index>=walking.path.length){blocky.reset();arrive();}
 }else if(walking.phase==='settle'){
  const tr=walking.transition;walking.elapsed+=dt;let t=Math.min(1,walking.elapsed/tr.duration),ease=t*t*(3-2*t);g.rotation.y=tr.yaw;g.position.lerpVectors(tr.from,tr.to,ease);if(tr.pose==='sleep'){const k=tr.loft?Math.max(0,(t-.65)/.35):ease;blocky.body.rotation.x=-Math.PI/2*k;blocky.body.position.z=.72*k;blocky.body.position.y=0;}else{blocky.body.position.y=-.32*ease;for(const l of blocky.legs)l.rotation.x=-Math.PI/2*ease;for(const a of blocky.arms)a.rotation.x=-.6*ease;}
  if(t===1){walking.phase='rest';walking.wait=0;setPersonStatus(tr.pose==='sleep'?'Resting on the bed':'Working at the desk',tr.pose==='sleep'?'Stop / stand up to get moving again.':'Taking a seat, six-block style.');}
 }else if(walking.phase==='rest'&&walking.routine){walking.wait+=dt;if(walking.wait>3){const routine=['desk','bathroom','balcony','bed','entrance'];walking.routineIndex=(walking.routineIndex+1)%routine.length;const prev=walking.action;if(prev){blocky.reset();g.position.set(prev.x,surfaceHeight(prev.x,prev.z)+.015,prev.z);}action(routine[walking.routineIndex],true);}}
 const x=g.position.x,z=g.position.z;const nearFront=Math.hypot(x,z-2.3)<1.2,nearBack=Math.hypot(x-1.65,z+2.3)<1.1,nearBath=Math.hypot(x+2.175,z-.05)<1.1;const factor=Math.min(1,dt*5);house.frontLeaf.position.x=T.MathUtils.lerp(house.frontLeaf.position.x,nearFront?.94:0,factor);house.rearPivot.rotation.y=T.MathUtils.lerp(house.rearPivot.rotation.y,nearBack?-1.4:0,factor);house.bathLeaf.position.x=T.MathUtils.lerp(house.bathLeaf.position.x,nearBath?.79:0,factor);
 if(follow&&mode==='simulate'&&camera===perspective){const desired=new T.Vector3(x,1,z);const delta=desired.sub(controls.target).multiplyScalar(dt*2.1);controls.target.add(delta);camera.position.add(delta);}
}
function checkPaths(){ensurePersonFree();const p=personPos();const lines=['bed','desk','bathroom','balcony','entrance'].map(name=>{const opts=destination(name,state.items),pass=opts.some(o=>findPath(p,o,state.items,personHeight));return{name,pass,exists:!!opts.length};});$('#pathResults').innerHTML=lines.map(r=>`<div><span>${r.name[0].toUpperCase()+r.name.slice(1)}</span><b class="${r.pass?'pass':'fail'}">${r.pass?'✓ Reachable':r.exists?'Blocked':'Not placed'}</b></div>`).join('');toast('Access checked from Blocky’s current position.');return lines;}

function exportLayout(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});download(blob,'House-Studio-Layout.json');toast('Layout exported. Keep this file as your portable backup.');}
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
function savedLayouts(){const values=readStorage('house-studio-layouts-v1',[]);return Array.isArray(values)?values:[];}
function renderSaved(){const layouts=savedLayouts();$('#savedLayouts').innerHTML=layouts.length?layouts.map((p,i)=>`<div class="saved-layout"><button data-load="${i}">${escapeHTML(p.name)}<small>${p.items?.length||0} objects</small></button><button class="icon-btn" data-remove-save="${i}" title="Delete saved copy" aria-label="Delete ${escapeHTML(p.name)}">${icon('trash')}</button></div>`).join(''):'<div class="empty-copy">No named copies yet.</div>';$$('[data-load]').forEach(b=>b.onclick=()=>{try{const s=validateLayout(layouts[Number(b.dataset.load)]);checkpoint();state=s;selectedId=null;commit();$('#layoutsDialog').close();toast('Saved layout loaded.');}catch(e){toast(e.message);}});$$('[data-remove-save]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this named copy? Your current layout stays unchanged.'))return;layouts.splice(Number(b.dataset.removeSave),1);writeStorage('house-studio-layouts-v1',layouts);renderSaved();});}
function present(active){document.body.classList.toggle('presentation',active);$('#exitPresent').hidden=!active;selectedId=null;updateSelection();$('#sidebar').classList.remove('mobile-open');resize();}
function screenshot(){renderer.render(scene,camera);renderer.domElement.toBlob(blob=>{if(blob)download(blob,'House-Studio-View.png');});toast('Scene image saved.');}

$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));$$('[data-light]').forEach(b=>b.onclick=()=>setLight(b.dataset.light));$$('[data-view]').forEach(b=>b.onclick=()=>view(b.dataset.view));$$('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
$('#roofBtn').onclick=()=>{showRoof=!showRoof;if(showRoof&&wallMode==='hidden'){wallMode='full';$('#wallSelect').value=wallMode;}applyVisibility();};$('#wallSelect').onchange=e=>{wallMode=e.target.value;applyVisibility();};$('#fitBtn').onclick=()=>view('iso');$('#lightsToggle').onchange=updateLights;$('#gardenToggle').onchange=e=>house.garden.visible=e.target.checked;
$('#measureBtn').onclick=toggleMeasure;$('#dimensionBtn').onclick=()=>{dimensionGroup.visible=!dimensionGroup.visible;$('#dimensionBtn').classList.toggle('active',dimensionGroup.visible);};$('#undoBtn').onclick=undo;$('#redoBtn').onclick=redo;$('#snapToggle').onchange=e=>{snap=e.target.checked;grid.visible=mode==='decorate'&&snap;renderInspector();};$('#searchInput').oninput=renderCatalog;
$('#heightInput').oninput=e=>{personHeight=Number(e.target.value)/100;$('#heightLabel').textContent=e.target.value+' cm';stopWalking();};$('#followToggle').onchange=e=>follow=e.target.checked;$('#pathToggle').onchange=e=>routeGroup.visible=e.target.checked;$('#stopPerson').onclick=()=>{const a=walking.action;if(a?.item&&walking.phase!=='walking'){blocky.root.position.set(a.x,surfaceHeight(a.x,a.z)+.015,a.z);}stopWalking();};$('#resetPerson').onclick=resetPerson;$('#checkPaths').onclick=checkPaths;
$('#cameraTourBtn').onclick=()=>{if(camera===ortho)view('iso');autoOrbit=!autoOrbit;$('#cameraTourBtn').innerHTML=icon(autoOrbit?'pause':'play');};$('#screenshotBtn').onclick=screenshot;$('#helpBtn').onclick=()=>$('#helpDialog').showModal();$('#referenceBtn').onclick=()=>{$('#helpDialog details').open=true;$('#helpDialog').showModal();};$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#saveBtn').onclick=()=>{renderSaved();$('#layoutsDialog').showModal();};$('#saveLayoutForm').onsubmit=e=>{e.preventDefault();const name=$('#layoutName').value.trim();if(!name)return;const list=savedLayouts();if(list.length>=25){toast('Export or remove a saved copy before adding more (limit 25).');return;}const data=JSON.parse(JSON.stringify({...state,name}));list.push(data);if(writeStorage('house-studio-layouts-v1',list)){renderSaved();toast('Named copy saved.');}else toast('Browser storage is full or unavailable. Export JSON instead.');};$('#exportBtn').onclick=exportLayout;$('#downloadLayoutBtn').onclick=exportLayout;$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;if(file.size>2e6){toast('Layout file is too large (maximum 2 MB).');return;}try{const value=validateLayout(JSON.parse(await file.text()));checkpoint();state=value;selectedId=null;commit();$('#layoutsDialog').close();toast('Layout imported.');}catch(err){toast('Import stopped: '+err.message);}};
$('#presentBtn').onclick=()=>present(true);$('#exitPresent').onclick=()=>present(false);$('#mobilePanelBtn').onclick=()=>$('#sidebar').classList.toggle('mobile-open');


// Structural editor: all changes persist in the same undoable/exportable layout as furniture.
const buildingParts=[['floor','Main floor / footprint'],['front-wall','Front wall'],['back-wall','Rear wall'],['left-wall','Left wall'],['right-wall','Right wall'],['bathroom','Bathroom — move entire room'],['balcony','Balcony'],['roof','Main roof'],['bath-roof','Bathroom roof'],['garden','Garden / surroundings']];
const paletteLabels={wall:'General walls',floor:'Main floor',foundation:'Foundation',bathWall:'Bathroom walls',bathFloor:'Bathroom floor',roof:'Main roof',bathRoof:'Bathroom roof',balcony:'Balcony deck',rail:'Balcony rails',door:'Doors',window:'Window glass',frame:'Door/window frames',trim:'Wall trim',garden:'Garden'};
const numericField=(key,label,value,min=-6,max=6,step=.05)=>`<label class="field-label">${label}<input type="number" data-build-field="${key}" min="${min}" max="${max}" step="${step}" value="${Number(value).toFixed(2)}"></label>`;
const colorField=(key,label,color)=>`<label class="field-label">${label}<input type="color" data-build-color="${key}" value="${color}"></label>`;
function structurePart(){return state.structure.openings.find(o=>o.id===selectedStructure)||state.structure.partitions.find(o=>o.id===selectedStructure);}
function selectStructure(id){selectedStructure=id;renderBuild();}
function moveBathroomContents(oldRoom,newRoom){const dx=newRoom.x-oldRoom.x,dz=newRoom.z-oldRoom.z,scaleX=newRoom.w/oldRoom.w,scaleZ=newRoom.d/oldRoom.d;
 for(const o of state.items){if(o.x>=oldRoom.x-oldRoom.w/2&&o.x<=oldRoom.x+oldRoom.w/2&&o.z>=oldRoom.z-oldRoom.d/2&&o.z<=oldRoom.z+oldRoom.d/2){o.x=newRoom.x+(o.x-oldRoom.x)*scaleX;o.z=newRoom.z+(o.z-oldRoom.z)*scaleZ;}}
}
function editStructure(mutator){const before=JSON.stringify(state.structure),oldRoom={...state.structure.bathroom};checkpoint();mutator(state.structure);const s=state.structure,b=s.bounds,q=s.bathroom;
 if(b.right-b.left<2||b.front-b.back<2||q.w<.8||q.d<.8||s.openings.some(o=>o.sill+o.h>3||o.sill+o.h<.3)){state.structure=JSON.parse(before);history.pop();updateHistory();renderBuild();toast('That edit would make the room too small or place an opening above the wall.');return;}
 if(q.x!==oldRoom.x||q.z!==oldRoom.z||q.w!==oldRoom.w||q.d!==oldRoom.d)moveBathroomContents(oldRoom,q);
 state.preset='custom';commit();}
function renderBuild(){const s=state.structure;if(!s)return;const parts=[...buildingParts,...s.openings.map(o=>[o.id,`${o.kind==='door'?'🚪':'▤'} ${o.id} · ${o.side}`]),...s.partitions.map((p,i)=>[p.id,`Interior wall ${i+1}`])];
 $('#buildList').innerHTML=parts.map(([id,name])=>`<button data-build-select="${escapeHTML(id)}" class="${selectedStructure===id?'active':''}"><span>${escapeHTML(name)}</span>${selectedStructure===id?'<small>EDITING</small>':'<small>→</small>'}</button>`).join('');
 $$('[data-build-select]').forEach(el=>el.onclick=()=>selectStructure(el.dataset.buildSelect));
 $('#buildPalette').innerHTML=Object.entries(paletteLabels).map(([key,label])=>`<label><input type="color" value="${s.colors[key]}" data-palette="${key}"><span>${label}</span></label>`).join('');
 $$('[data-palette]').forEach(el=>el.onchange=e=>editStructure(s=>s.colors[el.dataset.palette]=e.target.value));
 const b=s.bounds,q=s.bathroom,part=structurePart();let title='',content='';
 if(selectedStructure==='floor'){title='Main floor & outer walls';content=`<p class="small-note">Move any exterior wall independently by editing its boundary. Floor, roof and adjoining edges follow.</p><div class="row">${numericField('bounds.left','Left X',b.left,-5,2)}${numericField('bounds.right','Right X',b.right,-2,5)}</div><div class="row">${numericField('bounds.back','Rear Z',b.back,-5,2)}${numericField('bounds.front','Front Z',b.front,-2,5)}</div>${colorField('colors.floor','Floor color',s.colors.floor)}<p class="small-note">Width ${(b.right-b.left).toFixed(2)} m × depth ${(b.front-b.back).toFixed(2)} m.</p>`;}
 else if(['front-wall','back-wall','left-wall','right-wall'].includes(selectedStructure)){const k={'front-wall':'front','back-wall':'back','left-wall':'left','right-wall':'right'}[selectedStructure],colorKey=k+'Wall';title=k[0].toUpperCase()+k.slice(1)+' exterior wall';content=`<p class="small-note">Move this wall. The main floor and roof resize with it; openings retain their absolute positions until you move them.</p>${numericField('bounds.'+k,k==='front'||k==='back'?'Z position':'X position',b[k],-5,5)}${colorField('colors.'+colorKey,'This wall color',s.colors[colorKey]||s.colors.wall)}`;}
 else if(selectedStructure==='bathroom'){title='Entire bathroom';content=`<p class="small-note">Drag the bathroom in the 3D scene, or move and resize it here. The bathroom walls, floor, roof and openings move together. Re-align access doors after changing its position.</p><div class="row">${numericField('bathroom.x','Center X',q.x)}${numericField('bathroom.z','Center Z',q.z)}</div><div class="row">${numericField('bathroom.w','Width',q.w,.8,4)}${numericField('bathroom.d','Depth',q.d,.8,4)}</div>${colorField('colors.bathWall','Bathroom wall color',s.colors.bathWall)}${colorField('colors.bathFloor','Bathroom floor color',s.colors.bathFloor)}`;}
 else if(selectedStructure==='balcony'){title='Rear balcony';content=numericField('balcony.depth','Depth',s.balcony.depth,.5,3)+colorField('colors.balcony','Deck color',s.colors.balcony)+colorField('colors.rail','Rail color',s.colors.rail);}
 else if(selectedStructure==='roof'||selectedStructure==='bath-roof'){title=selectedStructure==='roof'?'Main roof':'Bathroom roof';const k=selectedStructure==='roof'?'roof':'bathRoof';content=colorField('colors.'+k,'Roof color',s.colors[k])+'<p class="small-note">The roof follows the underlying walls and floor dimensions automatically.</p>';}
 else if(selectedStructure==='garden'){title='Garden';content=colorField('colors.garden','Ground color',s.colors.garden);}
 else if(part?.kind){title=part.kind==='door'?'Door':'Window';const w=wallSpec(s,part.side);content=`<label class="field-label">Wall<select data-build-field="opening.side">${SIDES.map(side=>`<option value="${side}" ${part.side===side?'selected':''}>${side}</option>`).join('')}</select></label><div class="row">${numericField('opening.at',w.axis==='x'?'X position':'Z position',part.at)}${numericField('opening.w','Opening width',part.w,.4,3)}</div><div class="row">${numericField('opening.h','Height',part.h,.3,2.7)}${numericField('opening.sill','Sill height',part.sill,0,2.5)}</div>${colorField('opening.color','Individual '+part.kind+' color',part.color||s.colors[part.kind])}<p class="small-note">Drag this ${part.kind} in the 3D scene to slide it along its current wall. Moving a bathroom access door may require matching the adjacent wall opening.</p><button id="deleteStructure" class="btn secondary wide">Delete ${part.kind}</button>`;}
 else if(part){title='Interior wall';content=`<p class="small-note">Drag to move this wall. Change width and depth to extend it or turn it into a partition.</p><div class="row">${numericField('partition.x','Center X',part.x)}${numericField('partition.z','Center Z',part.z)}</div><div class="row">${numericField('partition.w','Width',part.w,.1,6)}${numericField('partition.d','Depth',part.d,.1,6)}</div><div class="row">${numericField('partition.h','Height',part.h,.3,3)}${numericField('partition.deg','Rotation °',(part.rot||0)*180/Math.PI,-360,360,15)}</div>${colorField('partition.color','Individual wall color',part.color)}<button id="deleteStructure" class="btn secondary wide">Delete wall</button>`;}
 else {title='Select a structure';content='<p class="helper">Choose a component to edit its size, position and color.</p>';}
 const issues=structuralIssues(s);if(issues.length)content+=issues.map(t=>`<p class="warning">${escapeHTML(t)}</p>`).join('');
 $('#buildInspectorTitle').textContent=title;$('#buildInspector').innerHTML=content;
 $$('[data-build-field]').forEach(el=>el.onchange=e=>{let value=el.type==='number'?Number(el.value):el.value;if(el.type==='number'&&(!Number.isFinite(value)||value<Number(el.min)||value>Number(el.max))){toast('Check the allowed dimension range.');renderBuild();return;}const path=el.dataset.buildField.split('.');editStructure(s=>{const target=path[0]==='opening'?s.openings.find(o=>o.id===selectedStructure):path[0]==='partition'?s.partitions.find(o=>o.id===selectedStructure):s[path[0]];if(!target)return;if(path[1]==='deg')target.rot=value*Math.PI/180;else {target[path[1]]=value;if(path[0]==='opening'&&path[1]==='side'){const wall=wallSpec(s,target.side);target.at=Math.min(wall.end-target.w/2-.1,Math.max(wall.start+target.w/2+.1,target.at));}}});});
 $$('[data-build-color]').forEach(el=>el.onchange=e=>{const path=el.dataset.buildColor.split('.');editStructure(s=>{if(path[0]==='opening'){s.openings.find(o=>o.id===selectedStructure).color=e.target.value;}else if(path[0]==='partition'){s.partitions.find(o=>o.id===selectedStructure).color=e.target.value;}else s.colors[path[1]]=e.target.value;});});
 if($('#deleteStructure'))$('#deleteStructure').onclick=()=>{editStructure(s=>{s.openings=s.openings.filter(o=>o.id!==selectedStructure);s.partitions=s.partitions.filter(o=>o.id!==selectedStructure);});selectedStructure='floor';renderBuild();};
}
function structureHit(e){ray(e);const hits=raycaster.intersectObjects([house.structure,house.full,house.cut,house.doors,house.roof,house.garden],true);for(const h of hits){let n=h.object;while(n){if(n.userData.structureId)return n.userData.structureId;n=n.parent;}}return null;}
function moveStructure(id,x,z){const s=state.structure,step=snap?.1:.01,round=n=>Math.round(Math.max(-5.5,Math.min(5.5,n))/step)*step;
 if(id==='bathroom'){const oldRoom={...s.bathroom};s.bathroom.x=round(x);s.bathroom.z=round(z);moveBathroomContents(oldRoom,s.bathroom);return true;}
 const opening=s.openings.find(o=>o.id===id);if(opening){const w=wallSpec(s,opening.side),low=w.start+opening.w/2+.1,high=w.end-opening.w/2-.1;opening.at=round(Math.max(low,Math.min(high,w.axis==='x'?x:z)));return true;}
 const wall=s.partitions.find(o=>o.id===id);if(wall){wall.x=round(x);wall.z=round(z);return true;}
 if(['front-wall','back-wall','left-wall','right-wall'].includes(id)){const key=id.split('-')[0],b=s.bounds;const raw=round(['left','right'].includes(key)?x:z);s.bounds[key]=Math.max(key==='right'?b.left+2:key==='front'?b.back+2:-5.5,Math.min(key==='left'?b.right-2:key==='back'?b.front-2:5.5,raw));return true;}return false;}
$('#addPartition').onclick=()=>{const id=uid();editStructure(s=>s.partitions.push({id,x:0,z:0,w:2,d:.15,h:3,rot:0,color:s.colors.wall}));selectStructure(id);toast('Interior wall added. Drag it or set exact dimensions.');};
for(const kind of ['Door','Window'])$('#add'+kind).onclick=()=>{if(state.structure.openings.length>=40){toast('Maximum 40 openings.');return;}const id=`${kind.toLowerCase()}-${Date.now().toString(36)}`;editStructure(s=>s.openings.push({id,kind:kind.toLowerCase(),side:'front',at:s.bounds.left+.7,w:kind==='Door'?.8:1,h:kind==='Door'?2:1.1,sill:kind==='Door'?0:1}));selectStructure(id);toast(kind+' added. Change its wall or position as needed.');};
$('#resetStructure').onclick=()=>{if(!confirm('Reset the house structure, doors, windows and all structural colors? Your furniture will remain unchanged.'))return;editStructure(s=>Object.assign(s,cloneStructure()));selectedStructure='floor';renderBuild();};
let lastStructurePreview=0;
renderer.domElement.addEventListener('pointerdown',e=>{if(mode!=='build'||e.button!==0||measureMode)return;const id=structureHit(e);if(!id)return;selectStructure(id);const p=pointAt(e);if(!p)return;
 const s=state.structure;const draggable=id==='bathroom'||['front-wall','back-wall','left-wall','right-wall'].includes(id)||s.openings.some(o=>o.id===id)||s.partitions.some(o=>o.id===id);
 if(!draggable)return;let center={x:p.x,z:p.z};if(id==='bathroom')center={x:s.bathroom.x,z:s.bathroom.z};else if(s.partitions.some(o=>o.id===id)){const o=s.partitions.find(o=>o.id===id);center={x:o.x,z:o.z};}
 buildDrag={id,pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,offsetX:center.x-p.x,offsetZ:center.z-p.z,started:false};controls.enabled=false;renderer.domElement.setPointerCapture(e.pointerId);
},true);
renderer.domElement.addEventListener('pointermove',e=>{if(!buildDrag||mode!=='build'||e.pointerId!==buildDrag.pointerId)return;
 if(!buildDrag.started){if(Math.hypot(e.clientX-buildDrag.startX,e.clientY-buildDrag.startY)<5)return;checkpoint();buildDrag.started=true;}
 const p=pointAt(e);if(!p)return;moveStructure(buildDrag.id,p.x+buildDrag.offsetX,p.z+buildDrag.offsetZ);
 if(performance.now()-lastStructurePreview>85){rebuildStructure();lastStructurePreview=performance.now();}
});
function finishBuildDrag(e){if(!buildDrag||e.pointerId!==buildDrag.pointerId)return;if(buildDrag.started){state.preset='custom';commit(false);}buildDrag=null;controls.enabled=true;}
renderer.domElement.addEventListener('pointerup',finishBuildDrag);
renderer.domElement.addEventListener('pointercancel',finishBuildDrag);
// Optional browser-native agent hooks reuse the same validated UI actions.
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});for(const tool of [{name:'read_house_layout',description:'Read the current house layout and furniture dimensions in metres.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>JSON.parse(JSON.stringify(state))},{name:'load_house_preset',description:'Replace furniture with a starting preset, keeping the change available in undo.',inputSchema:{type:'object',properties:{preset:{type:'string',enum:PRESETS.map(p=>p.id)}},required:['preset'],additionalProperties:false},execute:input=>{if(!input||!PRESETS.some(p=>p.id===input.preset))throw new Error('Unknown preset.');applyPreset(input.preset);return{name:state.name,objects:state.items.length};}}]){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}}}

rebuild();renderPresets();applyVisibility();setLight('day');updateHistory();resize();controls.update();save();
const clock=new T.Clock();function animate(){requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.05),time=clock.elapsedTime;if(cameraTransition){cameraTransition.t+=dt;const t=Math.min(1,cameraTransition.t/.65),e=t*t*(3-2*t);camera.position.lerpVectors(cameraTransition.from,cameraTransition.to,e);controls.target.lerpVectors(cameraTransition.targetFrom,cameraTransition.targetTo,e);if(t===1)cameraTransition=null;}controls.autoRotate=autoOrbit;controls.autoRotateSpeed=.60;controls.update(dt);if(mode==='simulate')updatePerson(dt,time);renderer.render(scene,camera);}animate();$('#loading').hidden=true;
window.addEventListener('error',e=>{console.error(e.error);toast('Something went wrong. Export your layout, then reload the page.');});
